name: Send email
on:
  push:
    branches:
      - main
jobs:
  email:
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: AlexisMateo/sendmail-action@5
        with:
          smtp-server: ${{ secrets.SMTP_SERVER }}
          smtp-server-port: ${{ secrets.SMTP_SERVER_PORT }}
          auth-user: ${{ secrets.AUTH_USER }}
          auth-password: ${{secrets.EMAIL_PASSWORD }}
          subject: correciones a ${{github.repository}}
          body: ${{github.context.payload}}
          from: ${{ secrets.EMAIL_FROM }}
          to: breitenmoser@cadwork.swiss
          is-tls: false
          commit-message: true
