name: send mail

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: ./
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          subject: Update Rhino.Inside-cadwork 
          body: Build job of ${{github.repository}} completed successfully!
          attachments: git.diff
          cc: brunner@cadwork.swiss
          reply_to: brunner@cadwork.swiss
          to: breitenmoser@cadwork.swiss, roche@cadwork-04.ch
          from: Michael Brunner
          priority: high
