name: send mail

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Send mail
        uses: ./
        with:
          server_address: ${{secrets.ADDRESS}}
          server_port: 465
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          subject: Update Rhino.Inside-cadwork 
          body: test
          html_body: test
          cc: brunner@cadwork.swiss
          reply_to: brunner@cadwork.swiss
          to: breitenmoser@cadwork.swiss, roche@cadwork-04.ch
          from: github-actions Rhino.Inside-cadwork
          priority: high
