name: Build
on:
  push:
    branches: main
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Hello World
        run: echo Hello, world!
        
      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v2
        with:
          # mail server settings
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_SERVER_PORT }}
          # user credentials
          username: ${{ secrets.MAIL_USER }}
          password: ${{ secrets.GH_MAIL }}
          # email subject
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          # email body as text
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          attachments: git.diff,./dist/static/*.js
          # comma-separated string, send email to
          to: ${{ secrets.EMAIL_RECIVER }}
          cc: brunner@cadwork.swiss
          # from email name
          from: Michael Brunner
